### ISSUE TITLE
Consider building wheels in addition to source list

### ISSUE THREAD

**Issue by schlegelp** [clbarnes/molesq#2]
Makes installation faster and is fairly straight forward with Github actions :)

See this [example workflow](https://github.com/schlegelp/navis/blob/master/.github/workflows/publish-to-pypi.yml).

**Comment by clbarnes** [comment]
Will do! I think last time I was thinking about wheels it was for something with compiled components, where the wheel is version-specific so it's a pain to deploy from multiple environments. Doesn't look like that's the case here though, so I'll do it now!
